version: "3.9"  # optional since v1.27.0
services:
  banking_api:
    build: . # build the Docker image 
    container_name: banking_api_application
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"